// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDCCelhLTwHF4AGThkm2DCdBR_kjw8h2c',
    appId: '1:287515092202:web:0080f11db6756d1627e393',
    messagingSenderId: '287515092202',
    projectId: 'froggyphoto-68db0',
    authDomain: 'froggyphoto-68db0.firebaseapp.com',
    storageBucket: 'froggyphoto-68db0.appspot.com',
    measurementId: 'G-WBGGJ1F5LP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkkS8pR34k18yHDbOAZhpXfJYruXrbrb4',
    appId: '1:287515092202:android:5859c507452c085927e393',
    messagingSenderId: '287515092202',
    projectId: 'froggyphoto-68db0',
    storageBucket: 'froggyphoto-68db0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq8VQR2xDVHG_iAbdLwKHftBGQtQmA7kc',
    appId: '1:287515092202:ios:a4971fcb7a114d7927e393',
    messagingSenderId: '287515092202',
    projectId: 'froggyphoto-68db0',
    storageBucket: 'froggyphoto-68db0.appspot.com',
    androidClientId: '287515092202-doreo05kur0li53b5j2skejbu5mbs2kk.apps.googleusercontent.com',
    iosClientId: '287515092202-jsg237n46ol9si3g0bgji4td04sbsh0b.apps.googleusercontent.com',
    iosBundleId: 'com.whelksoft.froggybooth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq8VQR2xDVHG_iAbdLwKHftBGQtQmA7kc',
    appId: '1:287515092202:ios:0bee23dc72cad31227e393',
    messagingSenderId: '287515092202',
    projectId: 'froggyphoto-68db0',
    storageBucket: 'froggyphoto-68db0.appspot.com',
    androidClientId: '287515092202-doreo05kur0li53b5j2skejbu5mbs2kk.apps.googleusercontent.com',
    iosClientId: '287515092202-lpa68l688l5e8raaat7r36krfo4t28h3.apps.googleusercontent.com',
    iosBundleId: 'com.whelksoft.froggybooth.RunnerTests',
  );
}
